### ISSUE TITLE
packmol-memgen run error

### ISSUE THREAD

**Issue by yrq3027** [callumjd/AMBER-Membrane_protein_tutorial#8]
Hi！
when I run "packmol-memgen --pdb 1bl8.pdb --lipids DOPE:DOPG --ratio 3:1 --keepligs", followed error thrown. 
Traceback (most recent call last):
  File "/root/anaconda3/bin/packmol-memgen", line 189, in <module>
    main(args)
  File "/data/amber20/lib/python3.8/site-packages/packmol_memgen/main.py", line 189, in main
    if args.apl_exp:
AttributeError: 'Namespace' object has no attribute 'apl_exp'

**Comment by callumjd** [comment]
This looks to be an issue related to packmol-memgen so I would post this to the Amber mailing list https://ambermd.org/MailingLists.php

Which version are you running? I have just tried your command with 2022-03-08 v1.2.3 and this ran without issue.
